### ISSUE TITLE
I started with a new SD card ... where do I get the content to make the M8 Headless work?

### ISSUE THREAD

**Issue by znmeb** [Dirtywave/M8Docs#5]
I have everything connected and uploaded the latest firmware. I can communicate with the Teensy and save projects to the SD card, but I can't load instruments or presets because there weren't any on the SD card - I started with a new one. Where do I get the initial data to copy to the SD card?

**Comment by znmeb** [comment]
Never mind - found it in the Discord

**Comment by jorisroling** [comment]
Do you mind sharing where I can find these?

**Comment by trailhead** [comment]
I am not finding this information on Discord.  I see mention of a resources channel but I do not see it.
