### ISSUE TITLE
Use with Adafruit display breakout?

### ISSUE THREAD

**Issue by pepijndevos** [Dirtywave/M8Docs#8]
It seems the device is based on the same display as this Adafruit module: https://www.adafruit.com/product/1770
Would be cool if you could have a non-headless DIY option.

**Comment by trash80** [comment]
It’s not based on an Adafruit product. It is not the same.

**Comment by pepijndevos** [comment]
If you are using this display https://github.com/Dirtywave/ILI9341_t3n it is the same one as in the adafruit product.
